### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by AndyZ2121** [KomX/ESPHome-Ready4Sky#3]
Прошу помощи! Целый день мучаюсь, в коде не силён. Постоянно ошибки... При установке примера конфига получаю: компонент skykettle не установлен... Ругается на строку skykettle и mac_address. Нужен рабочий конфиг для заливки в ЕСП32. Спасибо.

**Comment by KomX** [comment]
Помощь оказывается [здесь](https://t.me/esp32_r4s).
Заходите!
